project:
  type: website
  

website:
  title: "Ahmed Aredah"
  twitter-card: true
  open-graph: true
  reader-mode: true
  page-navigation: true

  
  

  navbar:
    right:
      - icon: github
        href: https://github.com/AhmedAredah
      - icon: twitter
        href: https://twitter.com/AhmedAredah

  page-footer: 
    left: "Copyright 2023, Ahmed Aredah" 
    right: 
      - icon: github
        href: https://github.com/AhmedAredah
      - icon: twitter 
        href: https://twitter.com/AhmedAredah 

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    toc-depth: 2
    toc-expand: 2
    max-width: 500px
    html-math-method: katex
    code-fold: false
    code-summary: "Show the code"